export { default as RegisterPage } from "./register/RegisterPage";
export { default as BagesPage } from "./bages/BagesPage";
export { default as LandingPage } from "./landing/LandingPage";
export { default as LoginPage } from "./login/LoginPage";
export { default as ProfilePage } from "./profile/ProfilePage";
export { default as UserGoalsPage } from "./userGoals/UserGoalsPage";
export { default as SeasonalGoals } from "./seasonalGoals/SeasonalGoalsPage";
export { default as SingleGoal } from "./goals/SingleGoal";
export { default as Goal } from "./goals/Goal";
